sudo apt-get install -y \
    build-essential \
    cmake \
    git \
    python3 \
    python3-pip \
    python3.12-venv \
    curl \
    wget \
    pkg-config \
    libboost-all-dev \
    libconsole-bridge-dev \
    liborocos-kdl1.5 \
    liborocos-kdl-dev \
    libpyside2-dev \
    pyqt5-dev \
    libshiboken2-dev \
    shiboken2 \
    libbz2-dev \
    libassuan-dev \
    libgpg-error-dev \
    sbcl \
    libassimp-dev \
    libpoco-dev \
    libtinyxml-dev \
    libtinyxml2-dev \
    libassimp-dev \
    libogre-1.9.0v5 \
    libyaml-cpp-dev \
    libogre-1.9-dev \
    libturbojpeg0-dev \
    libturbojpeg \
    libopencv-dev \
    libfltk1.3-dev \
    libgtk2.0-dev \
    libtool-bin \
    qtbase5-dev \
    qt5-qmake \
    libcurlpp-dev \
    liburdfdom-dev \
    liblz4-dev \
    libgtest-dev \
    liblog4cxx-dev \
    libgpgme-dev \
    libpcl-dev \
    sip-dev \
    python3-opengl \
    python3-defusedxml \
    python3-pyqt5.qtopengl \
    python3-pykdl \
    python3-pydot \
    python3-pygraphviz \
    python3-opencv \
    python3-matplotlib \
    python3-pycryptodome \
    python3-gnupg \
    python3-pyqt5.qtwebkit \
    python3-mock \
    python3-coverage \
    python3-empy \
    python3-psutil \
    python3-catkin-pkg \
    python3-rospkg \
    python3-nose \
    python3-yaml
